---
- name: "Download Kibana's deb"
  get_url:
    url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-amd64.deb"
    dest: "/tmp/kibana-{{ kibana_version }}-amd64.deb"
    validate_certs: false
  register: download_kibana
  until: download_kibana is succeeded
  delegate_to: localhost
- name: "Copy to Kibana server"
  copy:
    src: "/tmp/kibana-{{ kibana_version }}-amd64.deb"
    mode: 0755
    dest: "/tmp/kibana-{{ kibana_version }}-amd64.deb"