---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    groups:
      - kibana
provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        hosts:
          el-instance:
            ansible_host: 130.193.53.100
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy