---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: kibana
  gather_facts: false
  tasks:
    - name: Get kibana log
      ansible.builtin.slurp:
        src: /var/log/kibana/kibana.log
      register: kibanalog
    - set_fact:
        kibanalog: "{{ kibanalog['content'] | b64decode }}"
    - name: Example assertion
      assert:
        that:
          - "'http server running at http://0.0.0.0:5601' in kibanalog"
#